### ISSUE TITLE
write a statistic_image to file

### ISSUE THREAD

**Issue by yonestar** [canlab/CanlabCore#3]
Loading an image as a statistic_image and then trying to write it back to file in MNI space fails with the following error:

![image](https://cloud.githubusercontent.com/assets/4513934/8071261/67753f9c-0ec5-11e5-95a0-4d189a344af2.png)

A simple work-around is to load it as an fmri_data object, and then write to disk;  this works.

This error is likely limited to using the 'mni' flag w/ the statistic_image object

**Comment by wanirepo** [comment]
The 'mni' option in the write function involves resample_space, which might cause the error for statistic_image. I committed a small fix on that 8/4/15. Could you try this again and see if there is still an error?

**Comment by ljchang** [comment]
The ‘mni’ flag was sort of a kludgy hack to get the FOV in a space for other viewers.  It never worked for statistics_image() writes.  Thanks Wani for fixing that.  Luka and I added that awhile ago and that is something I was always meaning to fix.

**Comment by wanirepo** [comment]
I didn't do it. Tor made a change in "resample_space" to make it work for statistic_image, but there was a small problem, which I fixed. Hopefully the 'mni' option works for statistic_image for now. I haven't tested it. Yoni will let us know and close the issue, if it works.

**Comment by yonestar** [comment]
No, code still crashes when writing statistic_image with 'mni' flag.  Here
is the error:

>> write(t, 'fname', 'temp.nii', 'mni')
Index exceeds matrix dimensions.

Error in image_vector/resample_space (line 88)
   if ~isempty(obj.p), obj_out.p = p(Vto.wh_inmask, :); end

Error in image_vector/write (line 59)
    obj = resample_space(obj,mni);

**Comment by wanirepo** [comment]
It's now working. I fixed it by converting statistic_image into fmri_data before using resample_space.

**Comment by torwager** [comment]
hmmm, so resample_space is broken for statistic_image?

**Comment by wanirepo** [comment]
Actually, you added a comment saying that "this may break if nvox (total in
image) is different for 2 images..." in line 67 a while ago, and the
function exactly break there because of that exact reason (in Yoni's case).


On Wed, Aug 5, 2015 at 4:27 PM, Tor Wager <notifications@github.com> wrote:

> hmmm, so resample_space is broken for statistic_image?
>
> > On Aug 5, 2015, at 1:24 PM, Choong-Wan Woo <notifications@github.com>
> wrote:
> >
> > It's now working. I fixed it by converting statistic_image into
> fmri_data before using resample_space.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/canlab/CanlabCore/issues/3#issuecomment-128118513>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/canlab/CanlabCore/issues/3#issuecomment-128170181>.
>



-- 
Choong-Wan (Wani) Woo
Web <http://wanirepo.github.io/> | Code <https://github.com/wanirepo/> | Google
Scholar <https://scholar.google.com/citations?user=fZLY5H8AAAAJ&hl=en&oi=ao>
| Lab <http://wagerlab.colorado.edu/>
PhD candidate
Cognitive and Affective Neuroscience Lab
University of Colorado Boulder
